#--------------------------------------------
# GitHub Action Basic
#
# Copyright (c) by Aleksey Zhalnin 2023.
#--------------------------------------------

name: My-GitHubAction
env:
  APPLICATION_NAME: "Git2"
  DEPLOY_PACKAGE_NAME: "git2-deploy-ver-${{github.sha}}"

on:
  push:
    branches:
      - main

jobs:
  git2_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
      
    - name: Execute few commands
      run: |
        echo "Hello message#1"
        echo "Hello message#2"
        echo "Application name: ${{env.APPLICATION_NAME}}"
        
    - name: List current folder#1
      run: ls -la
      
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder#2
      run: ls -la
      
  git2_deploy:
    runs-on: ubuntu-latest
    
    needs: [git2_build]
    
    env: 
      VAR1: "This is Job level variable#1"
      VAR2: "This is Job level variable#2"
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"
      
    - name: Print env vars
      run: |
        echo " VAR1: ${{env.VAR1}}"
        echo " VAR2: ${{env.VAR2}}"
        echo " VAR3: $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Super local environment variable"
      
    - name: Print Deployment package
      run: echo "Deploy package name is ${{env.DEPLOY_PACKAGE_NAME}}"
      
    - name: Lets test some package iof there are here#1
      run: aws --version
      
    - name: Lets test some package if there are here#2
      run: zip --version
      
