#--------------------------------------------
# GitHub Action Basic
#
# Copyright (c) by Aleksey Zhalnin 2023.
#--------------------------------------------

name: My-GitHubAction
env:
  APPLICATION_NAME: "Git2"
  DEPLOY_PACKAGE_NAME: "git2-deploy-ver-$({github.sha})"

on:
  push:
    branches:
      - main

jobs:
  git2_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Testing job"
      
    - name: Execute few commands
      run: |
        echo "Hello message#1"
        echo "Hello message#2"
        echo "Application name: $({env.APPLICATION_NAME})"
      
  git2_deploy:
    runs-on: ubuntu-latest
    
    needs: [git2_build]
    
    steps:
    - name: Print Hello Message
      run: echo "Hello World from Deploy job"
      
    - name: Print Deployment package
      run: echo "Deploy package name is $({env.DEPLOY_PACKAGE_NAME})"
